#!/bin/bash

docker build --rm -t rabbitjupyter .
docker run --rm -d --network rabbit_net --hostname rabbitmq --name rabbit -p 15672:15672 -p 5672:5672 rabbitmq:3-management
docker run --rm --network rabbit_net --hostname rabbitmq --name jupyter -p 8888:8888 -v C:/users/ssloan/desktop/rabbit:/home/jovyan/work rabbitjupyter
